name: Deploy to Heroku

on:
  push:
    branches:
      - master  # or main, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Heroku Config Vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          CLOUDAMQP_URL: ${{ secrets.CLOUDAMQP_URL }}
        run: |
          heroku config:set CLOUDAMQP_URL=$CLOUDAMQP_URL --app ${{ secrets.HEROKU_APP_NAME }}
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
